server:
  port: 8080

spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: account
  cloud:
    zookeeper:
      connect-string: zookeeper:2181

logging:
  level:
    org.springframework.cloud.zookeeper: INFO