server:
  port: 8080

spring:
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
    gateway:
      routes:
      - id: registration-service
        uri: lb://account-registration-service
        predicates:
        - Path=/api/v1/account/**
      - id: balance-service
        uri: lb://account-balance-service
        predicates:
        - Path=/api/v1/balance/**
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.zookeeper: INFO

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"