server:
  port: 8082

spring:
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
    stream:
      kafka:
        streams:
          binder:
            brokers: kafka
            configuration:
              commit-interval.ms: 1000
          bindings:
            account-in:
              consumer:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
      bindings:
        account-in:
          destination: account
          consumer:
            header-mode: raw
          group: account-balance-group

logging:
  level:
    org.springframework.cloud.zookeeper: INFO

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"