server:
  port: 8082

spring:
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
    stream:
      kafka:
        streams:
          binder:
            brokers: kafka
          bindings:
            account-in:
              consumer:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
      bindings:
        account-in:
          destination: account
          consumer:
            header-mode: raw
          group: account-balance-group
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: account

logging:
  level:
    org.springframework.cloud.zookeeper: INFO

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"